language: node_js

node_js:
  - "node"

os:
  - linux
  - osx

env:
  - CODE_VERSION=1.26.0 # Minimal Version
  - CODE_VERSION=* # Last Stable Version
  - CODE_VERSION=insiders # Insider Version

cache:
  directories:
    - "node_modules"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish
  # For coverage, disable automatic start of extension
  - sed -i.bak 's/"\*"//g' package.json

script:
  - npm run style-check
  - npm test --silent

after_success:
  - bash <(curl -s https://codecov.io/bash)

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

jobs:
  include:
    - stage: release
      language: node_js
      node_js: "8"
      before_install: skip
      install:
        - npm install
      script:
        - npm run build
        - npm run semantic-release
      after_success: skip
  allow_failures:
    - env: CODE_VERSION=insiders
