jobs:
  - job: Windows
    strategy:
      matrix:
        Code26:
          CODE_VERSION: '1.26.0'
        CodeCurrent:
          CODE_VERSION: ''
        CodeInssiders:
          CODE_VERSION: 'insiders'
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
        inputs:
          keyfile: '**/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json'
          targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
          vstsFeed: '$(Npm-Cache)'
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
          command: 'custom'
          customCommand: 'i'
        condition: and(succeeded(), ne(variables['CacheRestored'], 'true'))
      - task: 1ESLighthouseEng.PipelineArtifactCaching.SaveCacheV1.SaveCache@1
        inputs:
          keyfile: '**/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json'
          targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
          vstsFeed: '$(Npm-Cache)'
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run build'
      - bash: sed -i.bak 's/"\*"//g' package.json
        displayName: 'Enable full coverage'
      - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreAndSaveCacheV1.RestoreAndSaveCache@1
        inputs:
          keyfile: '**/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json'
          targetfolder: '**/.vscode-test, !**/node_modules/**/.vscode-test'
          vstsFeed: '$(ArtifactFeed)'
      - task: Npm@1
        displayName: 'Run tests'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run test --silent'
      - task: PublishTestResults@2
        displayName: 'Publish Test Results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'test-reports/*.xml'
          mergeTestResults: true
          testRunTitle: '$(Agent.OS) $(Agent.JobName)'
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish Code Coverage to Azure'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/coverage/lcov-report'
      - script: node_modules\.bin\codecov --disable=gcov
        displayName: 'Publish Code Coverage to Codecov'
        env:
          CODECOV_TOKEN: $(codecovToken)
  - job: macOS
    strategy:
      matrix:
        Code26:
          CODE_VERSION: '1.26.0'
        CodeCurrent:
          CODE_VERSION: ''
        CodeInssiders:
          CODE_VERSION: 'insiders'
    pool:
      name: Hosted macOS
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
          command: 'custom'
          customCommand: 'ci'
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run build'
      - bash: sed -i.bak 's/"\*"//g' package.json
        displayName: 'Enable full coverage'
      - task: Npm@1
        displayName: 'Run tests'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run test --silent'
      - task: PublishTestResults@2
        displayName: 'Publish Test Results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'test-reports/*.xml'
          mergeTestResults: true
          testRunTitle: '$(Agent.OS) $(Agent.JobName)'
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish Code Coverage to Azure'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/coverage/lcov-report'
      - script: node_modules/.bin/codecov --disable=gcov
        displayName: 'Publish Code Coverage to Codecov'
        env:
          CODECOV_TOKEN: $(codecovToken)
  - job: Linux
    strategy:
      matrix:
        Code26:
          CODE_VERSION: '1.26.0'
        CodeCurrent:
          CODE_VERSION: ''
        CodeInssiders:
          CODE_VERSION: 'insiders'
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
          command: 'custom'
          customCommand: 'ci'
      - task: Npm@1
        displayName: 'Lint check'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run style-check'
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run build'
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: 'Start xvfb'
      - bash: sed -i.bak 's/"\*"//g' package.json
        displayName: 'Enable full coverage'
      - task: Npm@1
        displayName: 'Run tests'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run test --silent'
        env:
          DISPLAY: :10
      - task: PublishTestResults@2
        displayName: 'Publish Test Results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'test-reports/*.xml'
          mergeTestResults: true
          testRunTitle: '$(Agent.OS) $(Agent.JobName)'
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish Code Coverage to Azure'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/coverage/lcov-report'
      - script: node_modules/.bin/codecov --disable=gcov
        displayName: 'Publish Code Coverage to Codecov'
        env:
          CODECOV_TOKEN: $(codecovToken)
  - job: Release
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn:
    - Windows
    - macOS
    - Linux
    pool:
      name: Hosted Ubuntu 1604
      demands: npm
    steps:
      - task: NodeTool@0
        displayName: 'Use Node 8.x'
        inputs:
          versionSpec: 8.x
      - task: Npm@1
        displayName: 'Install dependencies'
        inputs:
          verbose: false
          command: 'custom'
          customCommand: 'ci'
      - task: Npm@1
        displayName: 'Compile sources'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run build'
      - script: |
          set -e
          /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
          disown -ar
        displayName: 'Start xvfb'
      - task: Npm@1
        displayName: 'Run semantic-release'
        inputs:
          command: custom
          verbose: false
          customCommand: 'run semantic-release'
        env:
          VSCE_TOKEN: $(vsceToken)
          GH_TOKEN: $(githubToken)
          GIT_AUTHOR_EMAIL: $(gitEmail)
          GIT_COMMITTER_EMAIL: $(gitEmail)
          GIT_AUTHOR_NAME: $(gitName)
          GIT_COMMITTER_NAME: $(gitName)
