version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "JohnstonCode"
    ignored_updates:
      - match:
          dependency_name: "@types/node"
